# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

can_bes_getter_index_c <- function(sudoku_df, index, nums) {
    .Call(`_sudoku_can_bes_getter_index_c`, sudoku_df, index, nums)
}

cant_bes_getter_c <- function(sudoku_df) {
    .Call(`_sudoku_cant_bes_getter_c`, sudoku_df)
}

cant_bes_lengths_c <- function(sudoku_df, cant_bes, nums) {
    .Call(`_sudoku_cant_bes_lengths_c`, sudoku_df, cant_bes, nums)
}

check_integrity_c <- function(sudoku_df, nums) {
    .Call(`_sudoku_check_integrity_c`, sudoku_df, nums)
}

element_checker_c <- function(sudoku_df, cant_bes, nums, dimension) {
    .Call(`_sudoku_element_checker_c`, sudoku_df, cant_bes, nums, dimension)
}

num_empties <- function(sudoku_df) {
    .Call(`_sudoku_num_empties`, sudoku_df)
}

logical_solver <- function(sudoku_df, verbose, nums) {
    .Call(`_sudoku_logical_solver`, sudoku_df, verbose, nums)
}

solve_backtracking <- function(sudoku_df, empties, verbose, nums) {
    .Call(`_sudoku_solve_backtracking`, sudoku_df, empties, verbose, nums)
}

