# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

not_in_row_c <- function(sudoku_df, row) {
    .Call(`_sudoku_not_in_row_c`, sudoku_df, row)
}

not_in_col_c <- function(sudoku_df, col) {
    .Call(`_sudoku_not_in_col_c`, sudoku_df, col)
}

not_in_box_c <- function(sudoku_df, box) {
    .Call(`_sudoku_not_in_box_c`, sudoku_df, box)
}

can_bes_getter_index_c <- function(sudoku_df, index) {
    .Call(`_sudoku_can_bes_getter_index_c`, sudoku_df, index)
}

cant_bes_getter_c <- function(sudoku_df) {
    .Call(`_sudoku_cant_bes_getter_c`, sudoku_df)
}

solve_backtracking_c <- function(sudoku_df, empties, verbose) {
    .Call(`_sudoku_solve_backtracking_c`, sudoku_df, empties, verbose)
}

check_integrity_c <- function(sudoku_df) {
    .Call(`_sudoku_check_integrity_c`, sudoku_df)
}

cant_bes_lengths_c <- function(sudoku_df, cant_bes) {
    .Call(`_sudoku_cant_bes_lengths_c`, sudoku_df, cant_bes)
}

